storageClass:
  enable: true
 
ingressNginx:
  enable: true
  createNamespace: true
  
externalSecrets:
  enable: true
  createNamespace: true
  
tekton:
  enable: true
  createNamespace: true
  
keycloakPostgresql:
  enable: true
  createNamespace: true

keycloak:
  enable: true
  createNamespace: true

edp:
  enable: true
  createNamespace: true

argocd:
  enable: true
  createNamespace: true
  
defectdojo:
  enable: true
  createNamespace: true
